### ISSUE TITLE
Todo category title name underlining issue on Windows

### ISSUE THREAD

**Issue by Zacky2613** [kennxdy/doddot#1]
There's an issue with the todo category title names where the underlining that works on linux (as seen in the gif in the README.md) doesn't work on Windows
![image](https://user-images.githubusercontent.com/84255182/219938245-15ad37d4-5e77-4880-9dd8-d48a4a21b65a.png)

OS: Windows 11
Potential Solution: Get rid of the underlining in its entirety for compatibility.

**Comment by nyndek** [comment]
Thanks, I fixed it.
